
export const ACTIVE_LISTING = 'activeListing';
export const ACTIVE_LISTING_CC = 'Active Listing';
export const ACTIVE_LISTINGS_CC = 'Active Listings';
export const ADD = 'add';
export const ADD_LISTING_CC = 'Add Listing';
export const ADDRESS_LINE_1 = 'Address Line 1';
export const ADDRESS_LINE_2 = 'Address Line 2';
export const ANSWER_CC = 'Answer';
export const AUTH0 = 'auth0';
export const CITY_CC = 'City';
export const CODE = 'code';
export const COLLAPSE_ALL_CC = 'Collapse All';
export const CREATE_NEW_LISTING = 'Create New Listing';
export const DELETE = 'DELETE';
export const DELETE_LISTING_CC = 'Delete Listing';
export const EDIT = 'edit';
export const EDIT_LISTING_CC = 'Edit Listing';
export const EMAIL = 'email';
export const EMAIL_CC = 'Email';
export const ERROR = 'ERROR';
export const EXPAND_ALL_CC = 'Expand All';
export const FAQS = 'FAQs';
export const FILE_BRACKET = 'file[]';
export const FREQUENTLY_ASKED_QUESTIONS_CC = "Frequently Asked Questions"
export const GET = 'GET';
export const ID = 'id';
export const INACTIVE_LISTINGS_CC = 'Inactive Listings';
export const LIMIT = 'limit';
export const LOGO_FILE = 'logo';
export const LOGO_FILENAME = 'logoFilename'
export const MAILING_ADDRESS = 'Mailing Address';
export const MENU_CC = 'Menu';
export const MENU_FILE = 'menu';
export const MENU_FILENAME = 'menuFilename'
export const MODE = 'mode';
export const MANAGE_MY_LISTINGS_CC = 'Manage My Listings';
export const MY_PROFILE_CC = 'My Profile';
export const NAME_CC = 'Name';
export const NO_LISTING_CREATED_CC = 'No Listing Created Yet.';
export const NO_LISTING_FOUND_CC = 'No listing found within that area.'
export const OFFSET = 'offset';
export const OPERATING_HOURS_CC = 'Operating Hours';
export const PIT_STOP_ADDRESS = 'pitStopAddress';
export const PIT_STOP_ADDRESS_CC = 'Pit Stop Address';
export const POST = 'POST';
export const PUT = 'PUT';
export const QUESTION_CC = 'Question';
export const SAVE_CC = 'Save';
export const SCHEDULES = 'schedules';
export const SIGN_OUT_CC = 'Sign Out';
export const SIGN_UP_CC = 'Sign Up';
export const STATE_CC = 'State';
export const SUCCESSFULLY_CREATED_LISTING_CC = 'Successfully created listing.'
export const SUCCESSFULLY_DELETED_LISTING_CC = 'Successfully deleted listing.'
export const SUCCESSFULLY_UPDATED_LISTING_CC = 'Successfully updated listing.'
export const TECHNICAL_DIFFICULTIES = "We're experiencing technical difficulties. Please try again later!";
export const TOTAL_COUNT = 'totalCount';
export const UPLOAD_LOGO_CC = 'Upload Logo';
export const UPLOAD_MENU_CC = 'Upload Menu';
export const VENDOR_EMAIL_CC = "Vendor's Email";
export const VENDOR_MENU_CC = "Vendor's Menu";
export const VENDOR_BUSINESS_NAME_CC = "Vendor's Business Name";
export const VENDOR_PROFILE_CC = "Vendor's Profile";
export const VENDOR_SIGN_IN_CC = "Vendor Sign In";
export const VENDOR_SIGN_UP_CC = "Vendor Sign Up";
export const ZIP_CODE_CC = 'Zip Code';
